version: '3.8'

volumes:
  display_db_vol:

services:
  display-api:
    container_name: container_display_serv
    build:
        context: .
    ports:
        - "5001:5001"
    depends_on:
            - display-db

    restart: always

  display-db:
    container_name: container_display_db
    image: mysql:8.0.29
    ports:
      - "32001:3306"
    environment:
        MYSQL_ROOT_PASSWORD: "trick123"
        MYSQL_DATABASE: "display_microservice"
        MYSQL_USER: "bigdata2022"
        MYSQL_PASSWORD: "trick123"

    volumes:
        - display_db_vol:/var/lib/mysql